name: "push to registry"
on:
  push:
    tags:
      - "*"
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build and tag the image
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build \
          --build-arg "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" \
          --build-arg "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER" \
          --build-arg "GITHUB_ACTOR=$GITHUB_ACTOR" \
          --build-arg "GITHUB_TOKEN=$GITHUB_TOKEN" \
          -t "$DOCKER_USERNAME/echo-server:latest" ./contrib/docker

      - name: confirming successful build of image
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker run --rm "$DOCKER_USERNAME/echo-server:latest" version

      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/echo-server
      # - name: authenticate docker
      #   shell: bash
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
      # - name: push to github packages
      #   shell: bash
      #   run: |
      #     docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/upstream-gen:latest"
